# Generated by Django 5.2.4 on 2026-07-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('services', models.TextField(blank=True)),
                ('other_service', models.CharField(blank=True, max_length=200)),
                ('satisfaction', models.CharField(blank=True, max_length=50)),
                ('liked', models.TextField(blank=True)),
                ('other_liked', models.CharField(blank=True, max_length=200)),
                ('heard', models.CharField(blank=True, max_length=50)),
                ('wellbeing', models.CharField(blank=True, max_length=50)),
                ('recommend', models.CharField(blank=True, max_length=50)),
                ('review', models.TextField()),
                ('suggestions', models.TextField(blank=True)),
                ('publish_permission', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
